# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    password_listener:
        class: AppBundle\EventListener\PasswordEncoderListener
        arguments: ["@security.password_encoder"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
